# Generated by Django 2.2.14 on 2020-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_duration', models.CharField(max_length=20)),
                ('instructor_name', models.CharField(max_length=20)),
                ('instructor_experiance', models.CharField(max_length=20)),
                ('start_date', models.DateField(max_length=20)),
                ('start_time', models.TimeField(max_length=20)),
            ],
        ),
    ]
